---
apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    app: bar
spec:
  selector:
    app: bar
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
        - name: bar
          image: bar:latest
          ports:
            - containerPort: 8080
