load('../../lib/Tiltfile', 'files', 'add_env_vars')

docker_build(
    'bar',
    context='../../',
    dockerfile='./Dockerfile',
)

# Load and modify the YAML
yaml_files = files('manifests/*.yaml')
for yaml_file in yaml_files:
    k8s_yaml(add_env_vars(yaml_file))

k8s_resource(
    'bar',
    objects=[
        'bar:serviceaccount',
        'bar-root-inbound:httproute',
        'bar:server',
    ],
    labels=['app'],
    resource_deps=['linkerd-control-plane']
)
