---
apiVersion: v1
kind: Service
metadata:
  name: baz
  labels:
    app: baz
spec:
  selector:
    app: baz
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baz
  labels:
    app: baz
spec:
  selector:
    matchLabels:
      app: baz
  template:
    metadata:
      labels:
        app: baz
    spec:
      containers:
        - name: baz
          image: baz:latest
          ports:
            - containerPort: 8080
