---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: baz
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: baz
  port: http-toxic # target the toxic server (defined in the service)
  proxyProtocol: HTTP/2
  accessPolicy: deny # deny all traffic by default
