---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: default
  labels:
    app: foo
spec:
  selector:
    app: foo
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 9090
      targetPort: 9090
      name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: default
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
      annotations:
        config.linkerd.io/proxy-enable-native-sidecar: "true"
    spec:
      serviceAccountName: foo
      containers:
        - name: foo
          image: foo:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: BAR_URL
              value: "bar:80"
            - name: BAZ_URL
              value: "baz:80"
            - name: USE_GRPC
              value: "false"