# Server Authorization
# https://linkerd.io/2-edge/reference/authorization-policy/#serverauthorization
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: default
  name: foo
spec:
  server:
    name: foo
  client:
    meshTLS:
      identities:
        - "ingress-nginx.ingress-nginx.serviceaccount.identity.linkerd.cluster.local"
