---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: foo
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: foo
  port: http
  proxyProtocol: HTTP/2
  accessPolicy: deny # deny all traffic by default

