---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bar
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  labels:
    app: bar
spec:
  selector:
    app: bar
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 9090
      targetPort: 9090
      name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
spec:
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
      annotations:
        config.linkerd.io/proxy-enable-native-sidecar: "true"
    spec:
      serviceAccountName: bar
      containers:
        - name: bar
          image: bar:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: BAZ_HTTP_URL
              value: "baz:80"
            - name: BAZ_GRPC_URL
              value: "baz:9090"
            - name: USE_GRPC
              value: "false"