# HTTP Inbound routes
# https://linkerd.io/2-edge/features/httproute/#inbound-and-outbound-httproutes
---
# prefix /
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: bar-root-inbound
  namespace: default
spec:
  parentRefs:
    - name: bar
      kind: Server
      group: policy.linkerd.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: bar-grpc-inbound
  namespace: default
spec:
  parentRefs:
    - name: bar-grpc
      kind: Server
      group: policy.linkerd.io
  rules:
    - backendRefs:
        - name: bar
          port: 9090
