# Server Authorization
# https://linkerd.io/2-edge/reference/authorization-policy/#serverauthorization
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: default
  name: bar
spec:
  server:
    name: bar
  client:
    meshTLS:
      identities:
        - "foo.default.serviceaccount.identity.linkerd.cluster.local"
