# Authorization Policy
# https://linkerd.io/2-edge/reference/authorization-policy/
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: foo-bar-authn
  namespace: default
spec:
  identities:
    - "foo.default.serviceaccount.identity.linkerd.cluster.local"
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  namespace: default
  name: foo-bar-authn
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: bar
  requiredAuthenticationRefs:
    - name: foo-bar-authn
      kind: MeshTLSAuthentication
      group: policy.linkerd.io
