ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.localhost

adminUser: admin
adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.linkerd-viz.svc.cluster.local:9090
        access: proxy
        isDefault: true
